// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmuicnlptuhrqzqjmnwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtdWljbmxwdHVocnF6cWptbndyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMjg0MDYsImV4cCI6MjA3MDYwNDQwNn0.z2eanbvhkxN9BchzEbLedvBQPP5V9eyaK1sF0CkCHDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});